name: voids_segmentation
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - keras=2.4.3
  - tensorflow=2.5
  - jupyterlab
  - ipywidgets
  - pytorch
  - torchvision
  - matplotlib
  - opencv
  - scikit-image
  - albumentations
  - pip
  - pip:
     - segmentation_models.pytorch
